#!/bin/sh
set -eu

: "${MIGRATOR_DATABASE_URL:?MIGRATOR_DATABASE_URL is required}"

psql "$MIGRATOR_DATABASE_URL" --set=ON_ERROR_STOP=1 <<'SQL'
GRANT USAGE ON SCHEMA public TO siftcut_api;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO siftcut_api;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO siftcut_api;
ALTER DEFAULT PRIVILEGES FOR ROLE siftcut_migrator IN SCHEMA public
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO siftcut_api;
ALTER DEFAULT PRIVILEGES FOR ROLE siftcut_migrator IN SCHEMA public
  GRANT USAGE, SELECT ON SEQUENCES TO siftcut_api;
SQL

node apps/api/dist/migrate.js
